server:
  port: 8080

external:
    api:
      key: "c%2BDZPcmLZOJJpGUtDSHeql60J4SrUEzdFpWkSw84BSCOegasdCl6g3%2BMmZNBi5PTMsYsUI%2BuGGs9zhu5lSVeTA%3D%3D"

spring:
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # 개발시에는 update, 실제 운영시에는 none을 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: user
      password: 1234

  redis:
    host: localhost
    port: 6379

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true